### ISSUE TITLE
NoSuchMethodError: java.util.Objects.isNull(Ljava/lang/Object;)Z

### ISSUE THREAD

**Issue by aalmiray** [robovm/robovm#1107] opened 2015-08-07 17:07 UTC
Encountered this error after the fix for #1106 was applied.

    [pool-2-thread-1] ERROR griffon.core.GriffonExceptionHandler - Uncaught Exception
    java.lang.NoSuchMethodError: java.util.Objects.isNull(Ljava/lang/Object;)Z
        at com.google.inject.internal.MembersInjectorImpl.notifyListeners(MembersInjectorImpl.java)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java)
        at 
    com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java)
        at com.google.inject.internal.InjectorImpl$2$1.call(InjectorImpl.java)
        at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java)
        at com.google.inject.internal.InjectorImpl$2.get(InjectorImpl.java)
        at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java)
        at griffon.javafx.AbstractJavaFXGriffonApplication.startup(AbstractJavaFXGriffonApplication.java)
        at griffon.javafx.JavaFXGriffonApplication$1.run(JavaFXGriffonApplication.java)

Unfortunately it's not possible for externals to run the test application linked at #1106 anymore due to changes made to Griffon 2.4.0-SNAPSHOT (iOS support, switch from `java.beans` to `openbeans`).

Copying `java.util.Objects` from OpenJDK8 (http://grepcode.com/file_/repository.grepcode.com/java/root/jdk/openjdk/8-b132/java/util/Objects.java/?v=source) didn't solve the problem :cry:

**Comment by aalmiray** [comment] 2015-08-07 21:01
I should mention that neither Griffon nor Guice make direct call to `Objects.isNull`.

**Comment by badlogic** [comment] 2015-08-07 21:10
We'll need a way to reproduce this on our end. I checked the classes mentioned in the stack trace, and they indeed don't call Objects.isNull. However, i would not be suprised if Guice's compile time AOP messes with it's own classes, e.g. weave in parameter asserts for it's internal methods.

If you can setup a repro case it'd be awesome. Otherwise you could try tracking down the .class file of MembersInjectorImpl and post the output of `javap -c MembersInjectorImpl`. Again, the class file contained in Guice's JAR may not be the final .class file that's linked with your app, due to Guice applying an AOP transform to it.

Side-note: sign up for  trial license key to get debugging and line number support. It's free, no strings attached, and we won't nag you :)

**Comment by aalmiray** [comment] 2015-08-07 21:18
Indeed. Though I'm using the `no_aop` version of Guice. Iwas able to find something inside the robovm cache, whose path looks like this `/Users/aalmiray/.robovm/cache/ios/x86/release/Users/aalmiray/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.0/199b7acaa05b570bbccf31be998f013963e5e752/guice-4.0-no_aop.jar/com/google/inject/internal/MembersInjectorImpl.class.o`. Don't know if this is the correct file to be looking at.

And I may take you on the license deal :smirk:

**Comment by badlogic** [comment] 2015-08-07 21:27
Ah, that file is the machine code RoboVM produces from the original class file. That class file is located inside the JAR at `Users/aalmiray/.gradle/caches/modules-2/files-2.1/com.google.inject/guice/4.0/199b7acaa05b570bbccf31be998f013963e5e752/guice-4.0-no_aop.jar`. That's "good" in so far, as it tells me that no weaving is applied to the `MembersInjectorImpl` methods. I checked the byte code of that class to make sure, using guice-4.0-no_aop.jar from the Guice release page. The method in question looks OK:

```
void notifyListeners(T, com.google.inject.internal.Errors) throws com.google.inject.internal.ErrorsException;
    Code:
       0: aload_2
       1: invokevirtual #20                 // Method com/google/inject/internal/Errors.size:()I
       4: istore_3
       5: aload_0
       6: getfield      #8                  // Field injectionListeners:Lcom/google/common/collect/ImmutableSet;
       9: invokevirtual #21                 // Method com/google/common/collect/ImmutableSet.iterator:()Ljava/util/Iterator;
      12: astore        4
      14: aload         4
      16: invokeinterface #22,  1           // InterfaceMethod java/util/Iterator.hasNext:()Z
      21: ifeq          65
      24: aload         4
      26: invokeinterface #23,  1           // InterfaceMethod java/util/Iterator.next:()Ljava/lang/Object;
      31: checkcast     #24                 // class com/google/inject/spi/InjectionListener
      34: astore        5
      36: aload         5
      38: aload_1
      39: invokeinterface #25,  2           // InterfaceMethod com/google/inject/spi/InjectionListener.afterInjection:(Ljava/lang/Object;)V
      44: goto          62
      47: astore        6
      49: aload_2
      50: aload         5
      52: aload_0
      53: getfield      #3                  // Field typeLiteral:Lcom/google/inject/TypeLiteral;
      56: aload         6
      58: invokevirtual #27                 // Method com/google/inject/internal/Errors.errorNotifyingInjectionListener:(Lcom/google/inject/spi/InjectionListener;Lcom/google/inject/TypeLiteral;Ljava/lang/RuntimeException;)Lcom/google/inject/internal/Errors;
      61: pop
      62: goto          14
      65: aload_2
      66: iload_3
      67: invokevirtual #28                 // Method com/google/inject/internal/Errors.throwIfNewErrors:(I)V
      70: return
    Exception table:
       from    to  target type
          36    44    47   Class java/lang/RuntimeException
```
The "bad" news is that we are back to square one. I'll need a reproduction case to say anything.

RoboVM is based on Android's runtime, which is somewhere between Java 6/7 API wise. `java.lang.Objects.isNull()` was introduced in Java 8, so neither Android nor RoboVM support that method. We'll need to figure out what's calling it, then make sure it's not calling it :)

**Comment by aalmiray** [comment] 2015-08-07 21:33
Right. I remember playing with robovm more than a year ago when only initial JKD7 support was ready. I had to provide my own version of `java.util.Objects` to make a simple app work. I tried the same approach again but didn't work this time.

I'll find a way to reproduce the problem without so much fluff. What I do know is that the error appears during (or around) a reflective call. What's funny is that up to that point other reflective code has been called already.

**Comment by aalmiray** [comment] 2015-08-07 21:37
FWIW found the culprit in the Griffon codebase. https://github.com/griffon/griffon/blob/development/subprojects/griffon-javafx/src/main/java/org/codehaus/griffon/runtime/javafx/controller/JavaFXGriffonControllerAction.java#L89-L92 This will be easy to fix :smirk:

**Comment by badlogic** [comment] 2015-08-07 23:38
Great, closing this issue then.

**Closed by badlogic** 2015-08-07 23:38 UTC

**Comment by aalmiray** [comment] 2015-08-09 12:57
Well, technically yes. The immediate problem was caused by a library that made use of JDK8 specific APIs. The real problem is caused by unsupported JDK8 APIs in robovom (which is a known issue).

**Comment by johanvos** [comment] 2015-08-09 18:19
Objects.isNull should work though, as it is in the compat.jar library that
accompanies jfxrt.jar and which contains some Java 8 functionality that is
used inside JavaFX 8.

2015-08-09 14:57 GMT+02:00 Andres Almiray <notifications@github.com>:

**Comment by ntherning** [comment] 2015-08-10 13:52
I'm afraid it doesn't work that way. :-( The `Objects` class we ship with RoboVM doesn't have the `isNull()` method. And even if you include one which has this method in the classpath the one in the RoboVM rt will take precedence since it is in the bootclasspath. The one in the classpath will be completely ignored. The only way to make it use the one in compat.jar is to specify compat.jar in the bootclasspath and make sure it's loaded before robovm-rt.jar.
