### ISSUE TITLE
 Couldn't compile app java.lang.IllegalArgumentException: Symbol [j]javax.naming.NamingException[infostruct] already defined

### ISSUE THREAD

**Issue by iitsoftware** [robovm/robovm#1007] opened 2015-06-04 09:37 UTC
I'm getting the following stack trace when compiling the above class with RoboVM 1.2.0 (Intellij plugin):

[DEBUG] Compiling javax.naming.NamingException (ios x86 release)
[ERROR] Couldn't compile app
java.lang.IllegalArgumentException: Symbol [j]javax.naming.NamingException[infostruct] already defined
	at org.robovm.compiler.ModuleBuilder.addGlobal(ModuleBuilder.java:87)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:791)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:287)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:241)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:330)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:374)
	at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)

**Comment by badlogic** [comment] 2015-06-04 09:48
Could you provide a reproduction case for this?

**Comment by iitsoftware** [comment] 2015-06-04 10:14
Use this jar file as library:

https://dl.dropboxusercontent.com/u/7771022/naming.jar

and, if required for compile, reference the class:

NamingException e = new NamingException();

> Am 04.06.2015 um 11:48 schrieb Mario Zechner <notifications@github.com>:
> 
> Could you provide a reproduction case for this?
> 
> On Thu, Jun 4, 2015 at 11:37 AM, iitsoftware <notifications@github.com>
> wrote:
> 
> > I'm getting the following stack trace when compiling the above class with
> > RoboVM 1.2.0 (Intellij plugin):
> >
> > [DEBUG] Compiling javax.naming.NamingException (ios x86 release)
> > [ERROR] Couldn't compile app
> > java.lang.IllegalArgumentException: Symbol
> > [j]javax.naming.NamingException[infostruct] already defined
> > at org.robovm.compiler.ModuleBuilder.addGlobal(ModuleBuilder.java:87)
> > at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:791)
> > at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:287)
> > at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:241)
> > at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:330)
> > at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:374)
> > at
> > org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
> > at
> > org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/robovm/robovm/issues/1007>.
> >
> —
> Reply to this email directly or view it on GitHub.
> 

-- 
Andreas Mueller
IIT Software GmbH, Bremen/Germany
http://www.swiftmq.com





IIT Software GmbH
Fahrenheitstr. 13, D28359 Bremen, Germany
Tel: +49 421 330 46 088, Fax: +49 421 330 46 090
Amtsgericht Bremen, HRB 18624, Geschaeftsfuehrer: Andreas Mueller
Steuernummer: 460/118/06404 VAT: DE199945912

**Comment by ntherning** [comment] 2015-06-05 09:14
I can reproduce. Boiled it down to to this `Exception` class:

```java
public static class FooException extends Exception {
    
    public void foo() throws FooException {
        throw new FooException();
    }
    
    public void bar() {
        try {
            foo();
        } catch (FooException e) {
            e.printStackTrace();
        }
    }
}

public static void main(String[] args) {
    FooException e = new FooException();
    System.out.println(e);
}
```

`FooException` has a catch clause which catches an instance of itself. `NamingException` in OpenJDK also has does this.

**Comment by ntherning** [comment] 2015-06-11 14:03
So I had to revert the fix since it breaks x86 32-bit builds. The linker fails with a `sectionForAddress(...) address not in any section file`. Will need to figure out another way to fix this.

**Comment by ntherning** [comment] 2015-06-11 14:55
Ok, new attempt at fix has been pushed. Please try with the latest nightly (20150612) once it's available at http://download.robovm.org. http://docs.robovm.com/advanced-topics/nightlies.html

**Comment by ntherning** [comment] 2015-06-17 09:07
Closing this as the OP notified me via private email that the problem is gone now.

**Closed by ntherning** 2015-06-17 09:07 UTC
