### ISSUE TITLE
Persistent "java.io.IOException: Cannot run program" during build

### ISSUE THREAD

**Issue by Guy-kun** [robovm/robovm#1203] opened 2015-11-25 02:26 UTC
I have a feeling this is related to the robovm plugin rather than robovm itself but am not sure where to report it now,

I keep getting a persistent "Cannot run program" whenever re-opening my robovm project for the first time in a day. The error does not go away on it's own, but usually after fiddling with settings it goes away (I really can't figure out what fixes it, usually a combination of opening/closing/restarting android studio & xcode, cleaning/ changing build targets, restarting iOS simulator and changing the running simulator type)

I do a lot of iOS development and usually have XCode running with another project but am not sure if this is related. The issue looks identical to XCode plugins not working but the exception is different hence I cannot find any other results on this

The exact error I get is:

```
[ERROR] Couldn't compile app
java.io.IOException: Cannot run program "2015-11-25 11:16:05:670 xcodebuild[85108:a0b] BBUncrustifyPlugin Version 2.1.3 loaded
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++": error=2, No such file or directory
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1047)
    at java.lang.Runtime.exec(Runtime.java:617)
    at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
    at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:246)
    at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:302)
    at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
    at org.robovm.compiler.util.Executor.exec(Executor.java:344)
    at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:371)
    at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:268)
    at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:391)
    at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:262)
    at org.robovm.compiler.Linker.link(Linker.java:422)
    at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:465)
    at org.robovm.compiler.AppCompiler.build(AppCompiler.java:776)
    at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
    at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)
Caused by: java.io.IOException: error=2, No such file or directory
    at java.lang.UNIXProcess.forkAndExec(Native Method)
    at java.lang.UNIXProcess.<init>(UNIXProcess.java:184)
    at java.lang.ProcessImpl.start(ProcessImpl.java:130)
    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1028)
    ... 15 more
```

Any help on this would be really appreciated as it's really frustrating to experience every day.
I am using Android Studio 1.5, RoboVM 1.11 and Xcode 7.1.1

**Comment by ntherning** [comment] 2015-11-25 08:16
You have some outdated Xcode plugin installed in Xcode which caused the issue. Duplicate of #959.

**Closed as completed by ntherning** 2015-11-25 08:16 UTC

**Comment by Guy-kun** [comment] 2015-11-25 08:22
@ntherning I don't think this is a duplicate, the log does not contain the following line:

```
2015-07-28 19:02:30.820 xcodebuild[1393:137286] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/CocoaPods.xcplugin' not present in DVTPlugInCompatibilityUUIDs
```

or any mention of plug-in compatibility.

Today I fixed this issue by restarting Android Studio but it's likely to re-surface tomorrow once more so I believe it is not related at all.
