### ISSUE TITLE
Running my app works, but debugging it causes it to crash immediately upon launch.

### ISSUE THREAD

**Issue by NoahAndrews** [robovm/robovm#1121] opened 2015-08-19 20:55 UTC
I have no clue what it could be that's causing this behavior, or where to look to find out. Debugging an app created freshly from the cross-platform template works as expected. This app has not always had this issue. Later I'll report back with what changed after the last commit where debugging worked.

**Comment by badlogic** [comment] 2015-08-19 20:57
Please add all information listed here: http://docs.robovm.com/errors.html

If possible, also give your machine specs and a reproduction sample so we
can reproduce it on our end.

**Comment by NoahAndrews** [comment] 2015-08-19 21:08
idea.log (RoboVM Studio 1.6)
https://drive.google.com/file/d/0B1MSp8fmGrzqTW1wSXV3TkNOXzg/view?usp=sharing

Specs
![image](https://cloud.githubusercontent.com/assets/10224994/9369052/d9171506-4694-11e5-9381-299176c912df.png)

Reproduction sample is unfortunately unavailable for now.

**Comment by badlogic** [comment] 2015-08-24 08:29
Hm, it looks like the simulator times out, meaning the app needs to long to start up. I'll need more information. Could you try these things:

1. Add `-rvm:log=debug` to your run configuration under program arguments, like this:
![http://sht.tl/iK9jDV](http://sht.tl/iK9jDV)
2. Run your app in debug mode on the simulator. Report the output in the console view, e.g.
![http://sht.tl/KwZVU5](http://sht.tl/KwZVU5)
3. Also report the contents of the file with the latest timestamp in the `robovm-build/logs` folder:
![http://sht.tl/8f6MXu](http://sht.tl/8f6MXu)

Once you reported the info, please try this:
1. Remove all breakpoints
2. Run in debug mode
3. Set a breakpoint in an event handler, e.g. a click listener.
4. Report if this works or not.

Also, make sure you do not do any excessive things before `UIApplicationDelegate#didFinishLaunching` is called. The simulator has a 30 seconds time-out. If that method doesn't get hit within that time-out, the process will get killed by the OS. Finally, make sure you keep the simulator open. Subsequent runs should start up faster, and hence counter-act the time-out.

**Comment by NoahAndrews** [comment] 2015-08-24 19:43
Considering that I'm now unable to reproduce, even when I revert to the commit I was at when I created the issue, I can't help any further. I will report back if I ever encounter this issue again. Part of the problem which triggered this condition may have been the data my server was giving the app.

**Comment by badlogic** [comment] 2015-08-25 08:34
Alright, thanks for reporting! I'll close this in the meantime. Should the problem turn up again, please post here again.

**Comment by NoahAndrews** [comment] 2015-09-14 02:24
I'm running into this problem again. Requested details: https://drive.google.com/folderview?id=0B1MSp8fmGrzqcHcyR2NUd0VYSUE&usp=sharing  

Debugging the app with only a single breakpoint in the login screen's  prepareForSegue method works as expected, as far as pausing execution when the breakpoint is hit. The app continues from there to not work normally, as it would without the debugger running.

**Comment by NoahAndrews** [comment] 2015-09-25 16:06
What does the ready label mean? That you've fixed the problem?

**Comment by badlogic** [comment] 2015-11-03 07:18
That it's actively being looked at. However, i was unable to reproduce the issue so far. Any way we can get a hand on the project?

**Comment by badlogic** [comment] 2015-11-10 09:54
@NoahAndrews any chance we could get our hands on your project? Without being able to reproduce it, we can't fix this issue.

**Comment by ItsHarper** [comment] 2015-11-10 17:51
I can ask my boss, but first I'd have to verify that I'm still having the issue. It only seems to occur when I'm debugging certain RxJava-heavy parts of the codebase, so I don't encounter it all of the time.

**Comment by badlogic** [comment] 2015-11-19 20:30
I'm making this a duplicate of #1175, let's discuss all the debugging issues there in one place. Hope that's OK!

**Closed by badlogic** 2015-11-19 20:30 UTC
Labels: bug, high, needsmoreinfo

**Comment by ItsHarper** [comment] 2015-11-19 21:55
Yep, that's great. Glad we're finally getting somewhere with this.
