### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Dunemaster** [robovm/robovm#1016] opened 2015-06-11 16:19 UTC
I'm trying to explore using UICollectionView from roboVm

the following code crashes:
https://gist.github.com/Dunemaster/27cacb771d5bfc446085

Crash message:

java.lang.ClassCastException: com._1c.platformBenchmark.ios.MyViewController$2 cannot be cast to org.robovm.objc.ObjCObject
	at org.robovm.objc.ObjCObject$Marshaler.protocolToNative(ObjCObject.java:375)
	at org.robovm.apple.uikit.UICollectionView.$m$setDataSource$(Native Method)
	at org.robovm.apple.uikit.UICollectionView.setDataSource(UICollectionView.java)
	at com._1c.platformBenchmark.ios.MyViewController.<init>(MyViewController.java)
	at com._1c.platformBenchmark.ios.Main.didFinishLaunching(Main.java)
	at com._1c.platformBenchmark.ios.Main.$cb$application$didFinishLaunchingWithOptions$(Main.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:368)
	at com._1c.platformBenchmark.ios.Main.main(Main.java)

Process finished with exit code 1

Am I doing something wrong?

**Comment by Dunemaster** [comment] 2015-06-11 16:26
Adding "extends NSObject" fixes the problem.
Maybe, you should mention it in some doc

**Comment by BlueRiverInteractive** [comment] 2015-06-11 16:54
This is a duplicate of: https://github.com/robovm/robovm/issues/353

Please use the adapter class (which extends from NSObject).

**Closed by BlueRiverInteractive** 2015-06-11 16:54 UTC
Labels: duplicate
