### ISSUE TITLE
Linker crash with RoboVM 1.3

### ISSUE THREAD

**Issue by statik** [robovm/robovm#992] opened 2015-05-28 17:22 UTC
Hi!

We have a project using RoboVM and Clojure, working pretty well under 1.2. We are building the project using the gradle robovm plugin. When I update to 1.3, we get a linker crash.

```
10:31:39.666 [ERROR] [org.gradle.BuildExceptionReporter] Caused by: java.lang.NullPointerException
10:31:39.667 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.robovm.compiler.Linker.createClassInfoErrorStruct(Linker.java:597)
10:31:39.668 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.robovm.compiler.Linker.link(Linker.java:233)
10:31:39.669 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:400)
10:31:39.669 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.robovm.compiler.AppCompiler.createIpa(AppCompiler.java:697)
10:31:39.670 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.robovm.gradle.tasks.CreateIPATask.invoke(CreateIPATask.java:54)
10:31:39.670 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
10:31:39.671 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
10:31:39.672 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
10:31:39.673 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
10:31:39.674 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
10:31:39.675 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
10:31:39.675 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
10:31:39.676 [ERROR] [org.gradle.BuildExceptionReporter] 	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
10:31:39.677 [ERROR] [org.gradle.BuildExceptionReporter] 	... 54 more
10:31:39.678 [ERROR] [org.gradle.BuildExceptionReporter]
```

I have tried with a minimal clojure/robovm project and do not get this linker crash. I decided to go ahead and report even though I don't have a public test case that I can point at yet.

**Comment by chgraham** [comment] 2015-05-28 19:26
@statik 
Could you supply your gradle build file (as a gist, or otherwise)?
I'm also interested in using Clojure together with RoboVM.
I'm no Gradle expert and would like to look at your build file to see if there's anything that I can learn from it. Thanks.

**Comment by statik** [comment] 2015-05-28 20:09
Hi! Here is a sample project that builds robovm+clojure with gradle,
although I haven't figured out what to add to it to reproduce the crash.
https://github.com/statik/robovm-bug-demo

-- 
Elliot Murphy

**Comment by ntherning** [comment] 2015-05-29 14:35
@statik Did you try clearing your RoboVM cache? `rm -rf ~/.robovm/cache/`. Try that, rebuild and let us know what happens. If it still crashes we'll need a reproduction case.

**Comment by statik** [comment] 2015-05-29 15:44
@ntherning thanks! I've tried clearing the cache and unfortunately it still crashes. I haven't had any success boiling down a standalone test case, I'll coordinate separately to give you access to the project.

**Comment by ntherning** [comment] 2015-06-01 08:54
This should be fixed now. I have started a new snapshot build which should be available in an hour or so. Please try it out and report back whether the NPE is gone. See http://docs.robovm.com/advanced-topics/nightlies.html#gradle for info on how to use the snapshots.

**Comment by ntherning** [comment] 2015-06-17 09:07
Closing since I believe it has been fixed now. Please reopen if you see the same problem once you get the chance to try it out.

**Closed by ntherning** 2015-06-17 09:07 UTC
