### ISSUE TITLE
NoSuchMethodError: sun.misc.Unsafe.putFloat

### ISSUE THREAD

**Issue by desertkun** [robovm/robovm#1105] opened 2015-08-06 15:39 UTC
Hello!

I've noticed that class sun.misc.Unsafe ins't fully supported:

    java.lang.NoSuchMethodError: sun.misc.Unsafe.putFloat

Please see the pull request to fix the issue (simply added missing putFloat/getFloat methods): https://github.com/robovm/robovm/pull/1100

**Comment by aalmiray** [comment] 2015-08-07 17:20
Duplicate of #1015

**Comment by desertkun** [comment] 2015-08-13 00:43
Yeah, it is. But original issue was created 2 month ago, and I've provided a pull request that fixes the issue, everything gets compiled as well.

Could you please merge this?

It's the only reason I didn't buy a license yet.

**Comment by ntherning** [comment] 2015-08-13 08:44
We'll try to merge it before the next release. In the meantime please use the PR to discuss this issue. I will close this and #1015 and refer both to the PR. Thanks!

**Closed by ntherning** 2015-08-13 08:44 UTC
