### ISSUE TITLE
File name too long when entering run sample for IOS

### ISSUE THREAD

**Issue by jymen** [robovm/robovm#1155] opened 2015-09-17 11:26 UTC
During compilation step of a sample ios/android project the compile step fails with a 'file name too long' error message.
my Environment : MACOS 10.10.5
XCode BETA 7.1 (7B60)

How to reproduce :
Create a new Android/XCode project 
Rebuild project => OK
Define an IOS configuration with default arguments
press the run button

log traces follow :

```
INFO] 31620 methods out of 31620 included in the executable
[INFO] Building ios binary /Users/jymen/RobovmstudioProjects/trekerapp/ios/robovm-build/tmp/trekerapp-ios/ios/x86_64/Main
[INFO] "2015-09-17 13:03:02.506 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XcodeExplorer.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.508 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XCode4_beginning_of_line.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.510 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.511 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ShowInGithub.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.513 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RevealPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.514 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PluginConsole.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.516 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OpenInTerminal.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.518 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMQuickHelp.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.519 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMColorSense.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.521 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/DocExpander.xcplugin' not present in DVTPlugInCompatibilityUUIDs
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++" -o 
[INFO]     /Users/jymen/RobovmstudioProjects/trekerapp/ios/robovm-build/tmp/trekerapp-ios/ios/x86_64/Main -arch x86_64 -Wl,-filelist,/Users/jymen/RobovmstudioProjects/trekerapp/ios/robovm-build/tmp/trekerapp-ios/ios/x86_64/objects0 -L /Users/jymen/.robovm-sdks/robovm-1.8.0/lib/vm/ios/x86_64 -ObjC -exported_symbols_list /Users/jymen/RobovmstudioProjects/trekerapp/ios/robovm-build/tmp/trekerapp-ios/ios/x86_64/exported_symbols -Wl,-no_implicit_dylibs -Wl,-dead_strip -fPIC -mios-simulator-version-min=8.0 -stdlib=libstdc++ -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -lrobovm-bc -force_load /Users/jymen/.robovm-sdks/robovm-1.8.0/lib/vm/ios/x86_64/librobovm-rt.a -lrobovm-debug -lrobovm-core -lgc -lpthread -ldl -lm -lz -liconv -lsqlite3 -framework Foundation -framework MobileCoreServices -framework UIKit -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks
[ERROR] Couldn't compile app
java.io.IOException: Cannot run program "2015-09-17 13:03:02.506 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XcodeExplorer.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.508 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XCode4_beginning_of_line.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.510 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/VVDocumenter-Xcode.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.511 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/ShowInGithub.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.513 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/RevealPlugin.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.514 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/PluginConsole.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.516 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OpenInTerminal.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.518 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMQuickHelp.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.519 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/OMColorSense.xcplugin' not present in DVTPlugInCompatibilityUUIDs
2015-09-17 13:03:02.521 xcodebuild[20012:6661048] [MT] PluginLoading: Required plug-in compatibility UUID 7FDF5C7A-131F-4ABB-9EDC-8C5F8F0B8A90 for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/DocExpander.xcplugin' not present in DVTPlugInCompatibilityUUIDs
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++": error=63, File name too long
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at java.lang.Runtime.exec(Runtime.java:620)
	at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:58)
	at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:246)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:302)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:149)
	at org.robovm.compiler.util.Executor.exec(Executor.java:344)
	at org.robovm.compiler.util.ToolchainUtil.link(ToolchainUtil.java:371)
	at org.robovm.compiler.target.AbstractTarget.doBuild(AbstractTarget.java:268)
	at org.robovm.compiler.target.ios.IOSTarget.doBuild(IOSTarget.java:390)
	at org.robovm.compiler.target.AbstractTarget.build(AbstractTarget.java:262)
	at org.robovm.compiler.Linker.link(Linker.java:421)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:465)
	at org.robovm.compiler.AppCompiler.build(AppCompiler.java:768)
	at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)
Caused by: java.io.IOException: error=63, File name too long
	at java.lang.UNIXProcess.forkAndExec(Native Method)
	at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
	at java.lang.ProcessImpl.start(ProcessImpl.java:134)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 15 more
```

![screen shot 2015-09-17 at 13 21 32](https://cloud.githubusercontent.com/assets/644653/9931878/aa6ec2a0-5d3f-11e5-9d5c-23707f1b30a8.png)

**Comment by jymen** [comment] 2015-09-17 11:53
FYI : This only appears Once ; I restarted Studio and the problem seemed to have disapeared ; I was able then to run and also making a debug build was succefull

**Comment by ntherning** [comment] 2015-11-25 08:17
You have some outdated Xcode plugin installed in Xcode which caused the issue. Duplicate of #959.

**Closed by ntherning** 2015-11-25 08:17 UTC
