### ISSUE TITLE
Debugger crashes immediately when trying to debug in a large project

### ISSUE THREAD

**Issue by alexitelman** [robovm/robovm#1175] opened 2015-10-21 07:54 UTC
We have a medium-large project with several modules (gradle) and 3rd-parties dependencies.
When running in 'debug' from IntelliJ the debugging doesn't actually work. 
The debugger is detached immediately and the breakpoints are not hit.
In a small sample project it works ok...

**Comment by badlogic** [comment] 2015-10-21 07:55
Simulator or device?

**Comment by alexitelman** [comment] 2015-10-21 07:55
Device. Didn't try on a simulator.
The device I'm using is iPhone 5s (arm64)

**Comment by badlogic** [comment] 2015-10-21 07:57
Please provide the debug log in robovm-logs.

**Comment by alexitelman** [comment] 2015-10-21 07:57
Where is it?

**Comment by alexitelman** [comment] 2015-10-21 08:09
?

**Comment by badlogic** [comment] 2015-10-21 08:10
in your project's folder. just grep for robovm-logs. depends on youe build system.

**Comment by alexitelman** [comment] 2015-10-21 08:44
I don't have robovm-logs :-(

**Comment by badlogic** [comment] 2015-10-21 08:49
Then something is wrong in your setup. Hard to tell without any kind of log
:/

**Comment by alexitelman** [comment] 2015-10-21 08:51
Where is the robovm-logs located usually??
Say my project is located in ~/sourceRoot and my robovm project is at ~/sourceRoot/robovmProj

**Comment by alexitelman** [comment] 2015-10-21 08:53
I have robovm-build/logs 
Is that what you meant?

**Comment by badlogic** [comment] 2015-10-21 09:04
yes, sorry. on vaccation, things are blurry :)

**Comment by alexitelman** [comment] 2015-10-21 09:07
Here's the log:
https://drive.google.com/file/d/0BwxZsZfwfINWaTFNZHNhek1DY3M/view?usp=sharing

**Comment by alexitelman** [comment] 2015-10-21 09:11
Here's another one with a different error:
https://drive.google.com/file/d/0BwxZsZfwfINWV3o5YndRWmNBdk0/view?usp=sharing

In this case when the debugger crashes the app on the iPhone gets stuck.

**Comment by badlogic** [comment] 2015-10-21 09:15
Hm, i see a few concerning things in there. I can't fix those here, i'll be
back at a computer next week.

I'll need a repro case. I see that the logging facade makes the debugger
unhappy (unknown base register). That doesn't crash the process though.
Something in $Proxy1 does, but we lack the fully qualified classpath name.

What Robo version are you using? I need that info to deobfuscate the stack
trace.

**Comment by alexitelman** [comment] 2015-10-21 09:18
1.9

On Wednesday, 21 October 2015, Mario Zechner <notifications@github.com>
wrote:

> Hm, i see a few concerning things in there. I can't fix those here, i'll be
> back at a computer next week.
>
> I'll need a repro case. I see that the logging facade makes the debugger
> unhappy (unknown base register). That doesn't crash the process though.
> Something in $Proxy1 does, but we lack the fully qualified classpath name.
>
> What Robo version are you using? I need that info to deobfuscate the stack
> trace.
> On Oct 20, 2015 11:11 PM, "alexitelman" <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> > Here's another one with a different error:
> >
> >
> https://drive.google.com/file/d/0BwxZsZfwfINWV3o5YndRWmNBdk0/view?usp=sharing
> >
> > In this case when the debugger crashes the app on the iPhone gets stuck.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/robovm/robovm/issues/1175#issuecomment-149829228>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/robovm/robovm/issues/1175#issuecomment-149830114>.
>


-- 
With regards,
      Alex Itelman
      054-8855550
P*   Think Green. Do you really need to print this document?*

**Comment by badlogic** [comment] 2015-10-21 09:21
Please try a 32-bit device build or a simualtor build. I won't be able to
fix this this week.

**Comment by badlogic** [comment] 2015-10-21 09:22
Please also try to disable the treeshaker

**Comment by alexitelman** [comment] 2015-10-21 09:23
how?

**Comment by badlogic** [comment] 2015-10-21 09:26
http://docs.robovm.com/configuration.html

**Comment by alexitelman** [comment] 2015-10-21 10:33
Tested on Simulator, 32-bit device, and without treeshaker.
Same result.

**Comment by alexitelman** [comment] 2015-10-21 11:33
Unfortunately I'm not able to create a sample for you.. it doesn't happen on any sample that I can think of. I don't know what could cause this..
But in the log I see a clear NPE.. So maybe try to fix that and I can test it on our project?

**Comment by alexitelman** [comment] 2015-10-27 15:00
Guys, any progress on this?

**Comment by badlogic** [comment] 2015-11-03 07:03
I wasn't able to reproduce this yet. Is there any way to get a hold of your project source off-channel?

**Comment by alexitelman** [comment] 2015-11-03 07:10
That would be tricky.. What I did in other cases is connect support to my computer via Team Viewer. We can do that if you agree. Contact me at alex@muvix.media if that's ok.

**Comment by badlogic** [comment] 2015-11-03 07:13
I need to be able to debug the debugger when it crashes, so screen sharing
is likely not going to help. I'll take you up on the offer if nothing else
helps!

**Comment by alexitelman** [comment] 2015-11-03 07:26
You can debug on my computer.. I can set up the environment and give you control.
Maybe try to catch that NPE first and let me try it?

**Comment by badlogic** [comment] 2015-11-03 07:28
We won't have access to the debugger sources on your end, and the setup to
debug the debugger is highly involved. I'm going to work off of the stack
traces you provided for now.

**Comment by alexitelman** [comment] 2015-11-03 07:32
I wiil try to build a sample that is similar to our project in its modules structure and dependencies

**Comment by badlogic** [comment] 2015-11-03 07:38
Thanks, really appreciate that.

**Comment by alexitelman** [comment] 2015-11-05 13:49
Still doesn't reproduce on a new project, very similar to ours.. weird.

**Comment by alexitelman** [comment] 2015-11-05 13:52
Upgrading to Gradle 2.8 only made this worse, now the app crashes on startup, not only the debugger.

**Comment by badlogic** [comment] 2015-11-05 14:00
This is extremely weird in so far, as Gradle should have zero influence on
the build when running via the IDE. I still can't reproduce this either.

**Comment by alexitelman** [comment] 2015-11-05 14:06
Yeah sounds weird to me too, so I switched back to 2.4 and the debugger crashes the app too, but it's a different device now - iPhone 4s with iOS 7, will try with the previous device again

**Comment by alexitelman** [comment] 2015-11-05 14:07
It crashes the app on the previous device too now :-(

**Comment by alexitelman** [comment] 2015-11-05 14:08
Same error in the robovm log

**Comment by alexitelman** [comment] 2015-11-09 17:15
ready? Did you fix something?

**Comment by ItsHarper** [comment] 2015-11-18 01:37
This sounds like it could be related to #1121.

**Comment by ItsHarper** [comment] 2015-11-18 01:42
Does your project happen to have much RxJava, lambdas, and/or Retrofit code in it? Those parts of my code seem most likely to crash the debugger.

BTW, the ready tag means that they're ready to work on it during this release cycle.

**Comment by alexitelman** [comment] 2015-11-18 07:00
Our code has a little Retrofit, but the debugger crashes immediately even without any breakpoints.. So this seems unrelated

**Comment by ItsHarper** [comment] 2015-11-18 14:12
I just tested debugging without breakpoints, and the debugger does crash/disconnect without them, once it hits a certain point in the code.

**Comment by badlogic** [comment] 2015-11-18 17:24
Can you try debugging on device without breakpoints?

**Comment by ItsHarper** [comment] 2015-11-18 17:40
Yes, it disconnects at the same point in the program execution.

**Comment by badlogic** [comment] 2015-11-18 22:59
Alright, please post the logs from the robovm-build/ folder in your
project. Please also let me know which RoboVM version you are using.
Ideally, we'd need a reproduction case so we can replay what's happening.

**Comment by ItsHarper** [comment] 2015-11-18 23:28
I uploaded a log file in issue #1121 about two months ago, but here's another one, this time from RoboVM 1.9.0. This is my most recent log, and I've confirmed that it ends approximately the same way as the one from two months ago. Let me know if you need any other of the logs in that folder for some reason.

I haven't talked to my boss about getting you access to our project yet, but I will do so on Friday.

https://drive.google.com/file/d/0B1MSp8fmGrzqMnhfUndVbzVRNFU/view?usp=sharing

**Comment by badlogic** [comment] 2015-11-19 10:29
Our proxy code is freaking out the debugger. RoboVM generates a $Proxy0 class for proxies, about which the debugger has no idea. We simply need to ignore any frames from $Proxy0.

**Comment by badlogic** [comment] 2015-11-19 10:43
Fixed $Proxy0, but now we can't find a thread:

```
[2015-11-19 11:42:07:975] DebugChannel - Event: Thread stopped, reason: Suspended, java obj: 0xbf904d0, thread: 0xbb39d80, frames: 5
[2015-11-19 11:42:07:975] SoftDebugger - Reconstructing frames took: 2.5122E-5secs
[2015-11-19 11:42:10:248] DebugChannel - Event: Thread stopped, reason: Suspended, java obj: 0xbfa2c60, thread: 0xbb39d00, frames: 2
[2015-11-19 11:42:10:250] SoftDebugger - Reconstructing frames took: 0.001551948secs
[2015-11-19 11:42:11:835] JdwpDebugServer - Command: ThreadReference_Status(11 4) id = 1592 length = 8
[2015-11-19 11:42:11:835] JdwpDebugServer - Command: StackFrame_ThisObject(16 3) id = 1594 length = 16
[2015-11-19 11:42:12:948] DebugChannel - Event: Thread detached, java obj: 0xc63ff20, thread: 0xbb39700, exception: 0x0
[2015-11-19 11:42:12:953] DebugChannel - Event: Thread stopped, reason: Suspended, java obj: 0xc63ff20, thread: 0xbb39700, frames: 1
[2015-11-19 11:42:12:960] SoftDebugger - Thread Thread-19 dettached
[2015-11-19 11:42:12:960] SoftJdwpEventProcessor - processing thread death event
[2015-11-19 11:42:12:960] SoftDebugger - com.robovm.debug.server.DebuggerException: Couldn't find thread for address 0xc63ff20
    at com.robovm.debug.server.soft.SoftDebugger.handleThreadStopped(SoftDebugger.java:289)
    at com.robovm.debug.server.soft.SoftDebugger.eventLoop(SoftDebugger.java:152)
    at com.robovm.debug.server.soft.SoftDebugger.access$000(SoftDebugger.java:48)
    at com.robovm.debug.server.soft.SoftDebugger$1.run(SoftDebugger.java:128)
    at java.lang.Thread.run(Thread.java:745)
[2015-11-19 11:42:12:960] SoftJdwpEventProcessor - processing vm death event
[2015-11-19 11:42:12:960] SoftDebugger - Shutting down event loop thread
[2015-11-19 11:42:12:961] JdwpDebugServer - Command: VirtualMachine_Dispose(1 6) id = 1598 length = 0
[2015-11-19 11:42:13:022] DebugLaunchPlugin - Shutting down JDWP server
```

**Comment by badlogic** [comment] 2015-11-19 10:48
IntellIJ IDEA by default stops all threads if one is suspended, e.g. due to a breakpoint or due to stepping. The above trace shows that all threads were suspended by IDEA, but one of them died before we could fetch the thread data itself.

**Comment by ItsHarper** [comment] 2015-11-19 14:51
Are you saying the debugger would crash whenever any networking code ran? 

Do you have a successful reproduction project, or do you still want me to try to get you access to my code?

**Comment by alexitelman** [comment] 2015-11-19 14:54
The debugger crashed when you used Retrofit specifically.
But this issue is fixed now, should be available in the next build.
So I don't think a sample is needed.
Now you just need to make sure your breakpoints are only suspending the current thread, not all, until this one is also fixed.

**Comment by ItsHarper** [comment] 2015-11-19 14:56
Sweet! I'll make sure to switch to the snapshot then! Thanks for finally nailing this down. :)

**Comment by alexitelman** [comment] 2015-11-19 14:57
Thanks to Mario :)

**Comment by alexitelman** [comment] 2015-11-19 14:57
Are you also using Retrofit?

**Comment by ItsHarper** [comment] 2015-11-19 15:23
Oh, I thought you were another team member for a minute, I didn't realize you were the OP. 

Who are you asking about Retrofit? Mario?

**Comment by alexitelman** [comment] 2015-11-19 15:27
No, you, Noah. Mario is not using Retrofit. I hope :)

**Comment by ItsHarper** [comment] 2015-11-19 15:30
Yes, I'm using it pretty heavily. (I assumed you weren't talking to me because I was the one who originally brought up that the parts of my code that use Retrofit seem to cause the crash)

**Comment by alexitelman** [comment] 2015-11-19 15:31
Oh, cool

**Comment by ItsHarper** [comment] 2015-11-19 17:43
@badlogic It appears you guys are about to release version 1.10! Will this fix be in that release, or did we miss it by a hair?

**Comment by badlogic** [comment] 2015-11-19 20:25
Hi,

we are actually about to release 1.11 :) However, the fix i applied for the $Proxy0 issue appears to be incomplete for your use case, but works for Alex' use case. I misunderstood how our proxies are generated :/ I applied a new fix which will be available in the 1.11.1-SNAPSHOT later tonight. Please give that a try tomorrow.

The second issue we identified today is that using Retrofit with IntelliJ IDEA's default breakpoint suspension behaviour (stop all threads) seems to be problematic. When you create a breakpoint, right click it, then set the suspension policy to `Thread`. This way only the thread where the breakpoint was hit will be stopped, while other threads continue running (this is the same model as in Eclipse). We'll have to fix this behaviour as well.

**Comment by badlogic** [comment] 2015-11-19 20:29
Triggered a build with the proper fix for the $Proxy issue, will be ready in 3 hours from now. You can get the latest IDEA plugin from here: http://download.robovm.org/files.html. You want the file called nightlies/idea/org.robovm.idea-1.11.1-SNAPSHOT-plugin-dist-XXXXX.jar (the XXXX will change)

**Comment by ItsHarper** [comment] 2015-11-19 22:59
Is there going to be a new RoboVM Studio release based on IDEA 15 stable?

**Comment by badlogic** [comment] 2015-11-19 23:41
Jupp!

**Comment by badlogic** [comment] 2015-11-20 07:54
@NoahAndrews we also have a snapshot build with the proper fix for the `$Proxy` issue, see http://download.robovm.org/files.html, specifically the file http://download.robovm.org/nightlies/robovm-studio/robovm-studio-1.11.1-SNAPSHOT.dmg

**Comment by ItsHarper** [comment] 2015-11-20 19:06
I'm extremely relieved to say that this bug seems to have been squashed :)

**Comment by badlogic** [comment] 2015-11-21 12:09
Great! Please let me know if you run into other debugging issues. We may
still have an issue with highly concurrent apps. I will only be able to fix
those with repro cases (and a bottle of Vodka to calmn my nerves :))

**Comment by alexitelman** [comment] 2015-12-06 11:39
Don't forget about the issue with breaking all threads :) or at least I think you should document that the user should set the breakpoints to break only current thread.

**Comment by badlogic** [comment] 2015-12-15 08:23
Since the original issue is fixed, i will close this. I opened another issue for the stop-all-threads policy issue in IDEA, see https://github.com/robovm/robovm/issues/1213

**Closed by badlogic** 2015-12-15 08:23 UTC
Labels: bug, high, needsmoreinfo, ready
