### ISSUE TITLE
Debugger crashes after some time

### ISSUE THREAD

**Issue by alexitelman** [robovm/robovm#1223] opened 2015-12-31 15:38 UTC
After debugging for some time (sometimes minutes, sometimes seconds) the debugger crashes (disconnects), and the app hangs.

IDE: IntelliJ IDEA 15.0.2 
RoboVM version: 12.0
Machine: MacBook Pro
Device: iPhone 5s (64-bit) + iOS 9.2
Configuration: Attached Device (arm64)

Attached robovm debug log:
https://drive.google.com/file/d/0BwxZsZfwfINWQUMzYVY2WGh5c1k/view?usp=sharing

Happy new year! :-)

**Comment by badlogic** [comment] 2016-01-11 11:39
The debugger tries to retrieve a thread that's already been detached. This should not happen if the debugger event ordering is correct.

Any chance we could get a repro case? I can only go by the log, but can't reproduce the issue locally.

**Comment by alexitelman** [comment] 2016-01-11 11:44
It will be very difficult and time consuming to make a repro case. 
We had this discussion in the past.
You can send us a special version with more debug prints.

**Comment by badlogic** [comment] 2016-01-11 11:57
I'll try to come up with something. Could you maybe just describe the threading in your app? I assume you do a lot of async work via RxJava?

**Comment by alexitelman** [comment] 2016-01-11 12:15
We have several threads running, some are related to audio processing, some to streaming, some to REST requests.. We're not using RxJava, just plain old Threads, wrapped in our own wrapper.

**Comment by alexitelman** [comment] 2016-01-11 12:16
The REST requests are with Retrofit.

**Comment by alexitelman** [comment] 2016-01-11 12:18
Also some threads do our own internal TCP communication..

**Comment by badlogic** [comment] 2016-01-11 12:52
OK, thanks for the info. If you find the time, could you debug the app, supplying the following vm argument:

```
-rvm:log=debug
```

That will print info from the VM itself, intermingled with your own logging. If you could send me both the log output from the app with the flag, and the debug log file in case of a crash, that'd be awesome.

**Comment by alexitelman** [comment] 2016-01-11 15:06
When I add this in the run configuration in the Program arguments, all hell brakes loose.. 
The compilation fails:

```
[INFO] Building null slice
[ERROR] Couldn't compile app
java.lang.NullPointerException
    at org.robovm.compiler.AppCompiler.build(AppCompiler.java:787)
    at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
    at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)
```

And when I get back to edit the configurations the 'Program arguments' is empty and the configuration switched from "Device" to "Simulator" by itself.

**Comment by alexitelman** [comment] 2016-01-12 09:30
Ok, I has a problem with Xcode that it didn't show any simulators, once I resolved that, the above problem went away and I'm able to run with the VM args. (Maybe you should check that just in case.. what happens in your code if there are no simulators).

**Comment by badlogic** [comment] 2016-01-12 13:15
OK, glad you figured it out. I'll see if we can detect and report the issue you ran into properly. 

I've tried to reproduce this all day yesterday and this morning, but my test doesn't provoke the event ordering you ran into. Let me know when you had the time to gather new logs.

**Comment by alexitelman** [comment] 2016-01-12 14:45
Here's the console output:

[robovm-debugger-extra-log.txt](https://github.com/robovm/robovm/files/87436/robovm-debugger-extra-log.txt)

And here's the debug log:

[debug_2016-01-12-112733.txt](https://github.com/robovm/robovm/files/87437/debug_2016-01-12-112733.txt)

**Comment by badlogic** [comment] 2016-01-13 10:57
Thanks, i'll see what i can derive from that. Worst case we'll have to have another screen sharing session.

**Comment by badlogic** [comment] 2016-01-13 11:10
Are you using the "stop all threads" policy on the breakpoint in for the run you submitted the logs for?

**Comment by badlogic** [comment] 2016-01-13 11:22
It appears that there's more Java code executed after we send the thread detach event in `thread.c:detachThread`. If a suspend request is processed after that for this thread (which is possible because the debugger hasn't received the death event yet), then the hook is processed and sends a "suspended" event to the debugger. However, due to TCP ordering, the original detach event is then processed before the suspend event. Since the debugger removes the thread from its internal list on a detach event, the suspend event processing fails. We need to make sure the detach event is send after all Java code is executed in the `detachThread` code.

**Comment by alexitelman** [comment] 2016-01-13 11:36
I just noticed that the breakpoint is suspend all threads.. But I changed
the default to thread earlier... :(
Maybe it was reset at some point.
I will try debugging again now..

On Wednesday, 13 January 2016, Mario Zechner notifications@github.com
wrote:

> It appears that there's more Java code executed after we send the thread
> detach event in thread.c:detachThread. If a suspend request is processed
> after that for this thread (which is possible because the debugger hasn't
> received the death event yet), then the hook is processed and sends a
> "suspended" event to the debugger. However, due to TCP ordering, the
> original detach event is then processed before the suspend event. Since the
> debugger removes the thread from its internal list on a detach event, the
> suspend event processing fails. We need to make sure the detach event is
> send after all Java code is executed in the detachThread code.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/robovm/robovm/issues/1223#issuecomment-171259313.

## 

With regards,
      Alex Itelman
      054-8855550
P\*   Think Green. Do you really need to print this document?*

**Comment by badlogic** [comment] 2016-01-13 11:46
I was able to reproduce the issue locally. I'll try to create a fix until EOD and will build a snapshot for you if you have time to test. Thanks for all the help with this!

**Comment by badlogic** [comment] 2016-01-13 12:44
Can confirm that this is fixed now. I triggered a new build which should be available in an hour or two from now.

**Closed as completed by badlogic** 2016-01-13 12:44 UTC
Labels: needsmoreinfo

**Comment by badlogic** [comment] 2016-01-13 12:45
Reference to fix robovm/robovm-core@fc84f92ebb11fcba2d27285141658cc526eee32b

**Comment by alexitelman** [comment] 2016-01-13 13:09
Ok, will try.
Is there an "Attach to process" feature planned? Would be nice.

**Comment by alexitelman** [comment] 2016-01-13 14:38
There's no nightly for the IDEA plugin anymore?

**Comment by alexitelman** [comment] 2016-01-13 14:43
Anyway, I can't reproduce the issue with the Suspend Thread breakpoints.. the debugger works fine.
Does your fix solve the Suspend All problem?

**Comment by alexitelman** [comment] 2016-01-13 14:49
Any chance you can look into attaching to process from Xcode not working?

**Comment by badlogic** [comment] 2016-01-13 15:07
It might have fixed the suspend threads on breakpoint issue, but that's harder to test for me. It definitely fixes the crash you reported in the debugger.

Concerning attaching to the process. There's two sides to this. One is on the Java side, and the other is via Xcode. The former is currently not planned, as the setup for that is very complicated in an AOT setting. The latter works for simulator builds, but doesn't work for device builds if you attach both the Java debugger and the Xcode debugger. The reason is that we ourselves need to use lldb to attach to the device when deploying the app. One way to use the Xcode debugger is to deploy the app, then start it manually from the phones spring board, then attach Xcode, without the Java debugger being attached.

The nightly is still building, you'll be able to find it here: http://download.robovm.org/files.html , should look something like nightlies/idea/org.robovm.idea-1.12.1-SNAPSHOT-plugin-dist-$DATA-$BUILD_NUMBER.jar. Go by the file date.

**Comment by alexitelman** [comment] 2016-01-13 15:11
I tried what you suggested from Xcode and it doesn't work, the app just freezes. I started the app from the phone, not from IntelliJ.
Is this something you'll be willing to look into?

**Comment by badlogic** [comment] 2016-01-13 15:23
This used to work (with some caveats). It's not an official feature, but
i'll give it a quick look tomorrow.
