### ISSUE TITLE
Network interfaces java API not working in a 64-bit binary

### ISSUE THREAD

**Issue by alexitelman** [robovm/robovm#1137] opened 2015-09-01 06:27 UTC
Hello,

The following java API is not working when running on a 64-bit device (iPhone 5s) with the arm64 robovm run configuration:

```
NetworkInterface.getNetworkInterfaces()
```

This is the error it produces:

```
java.net.SocketException
	at java.net.NetworkInterface.rethrowAsSocketException(NetworkInterface.java:236)
	at java.net.NetworkInterface.collectIpv4Address(NetworkInterface.java:226)
	at java.net.NetworkInterface.getByName(NetworkInterface.java:145)
	at java.net.NetworkInterface.getNetworkInterfacesList(NetworkInterface.java:331)
	at java.net.NetworkInterface.getNetworkInterfaces(NetworkInterface.java:286)
	at com.mycompany.myapp.MyViewController.getNetworkInterfacesCount(MyViewController.java:35)
	at com.mycompany.myapp.MyViewController.clicked(MyViewController.java:27)
	at com.mycompany.myapp.MyViewController.$cb$clicked(MyViewController.java)
	at org.robovm.apple.uikit.UIApplication.main(Native Method)
	at org.robovm.apple.uikit.UIApplication.main(UIApplication.java:369)
	at com.mycompany.myapp.Main.main(Main.java:17)
Caused by: libcore.io.ErrnoException: ioctl failed: EOPNOTSUPP (Operation not supported on socket)
	at libcore.io.Posix.ioctlInetAddress(Native Method)
	at libcore.io.ForwardingOs.ioctlInetAddress(ForwardingOs.java:83)
	at java.net.NetworkInterface.collectIpv4Address(NetworkInterface.java:204)
	... 9 more
```

If running it on the same device with the thumbv7 configuration it works fine (emulated 32-bit on the 64-bit device).

Here's a sample project illustrating the problem:
https://drive.google.com/file/d/0BwxZsZfwfINWYTV4S3NkcjJYWTA/view?usp=sharing

Thanks,
Alex.

**Comment by badlogic** [comment] 2015-09-01 13:21
It appears that for that one interface, IPv4 is not available, only IPv6. We could catch that, and only report IPv6, what do you think @ntherning ?

**Comment by alexitelman** [comment] 2015-09-01 14:05
What do you mean that *one* interface? it's supposed to return a list of interfaces.. on armv7 it returns 10 interfaces.

**Comment by badlogic** [comment] 2015-09-09 07:48
I can reproduce this on x86_64 on the simulator as well.

**Comment by badlogic** [comment] 2015-09-09 08:09
`ioctl` fails in the posix layer when probing the fd of the interface `lo0`:

![http://sht.tl/tfgi4u](http://sht.tl/tfgi4u)

It looks like the loopback device has no IP4 address associated with it, which makes `ioctl` fail.

**Comment by badlogic** [comment] 2015-09-09 08:23
Getting the same issue on x86 sim, but for a different network interface (virtualbox bridge):

```
vboxnet0: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:00 
	inet 192.168.56.1 netmask 0xffffff00 broadcast 192.168.56.255
```

**Comment by badlogic** [comment] 2015-09-09 12:05
`ioctl` seems to be super eratic depending on CPU arch and iOS device type. I'll fix it up by using `getifaddr` instead like we do for ipv6.

**Comment by badlogic** [comment] 2015-09-09 12:31
This should be fixed in the next nightly build.

**Comment by alexitelman** [comment] 2015-09-09 14:04
Great! will check it out tomorrow and let you know

**Comment by badlogic** [comment] 2015-09-09 14:44
Re-opened, unit test fails, test app works.

**Comment by alexitelman** [comment] 2015-09-09 17:40
So it won't be available tomorrow?

**Comment by badlogic** [comment] 2015-09-09 19:02
It will be solved, was a fluke on the build server. I triggered a build, should be available in an hour from now.

**Closed by badlogic** 2015-09-09 19:02 UTC
Labels: bug

**Comment by alexitelman** [comment] 2015-09-10 06:39
Is there a new link for downloading builds?
The old one is not working anymore, it leads to the Robovm Studio download page:
download.robovm.org

**Comment by badlogic** [comment] 2015-09-10 06:40
Yes, http://download.robovm.org/index.html. We are cleaning that up atm.

**Comment by alexitelman** [comment] 2015-09-10 08:03
This one seems to be fixed, great, but now we have another failure later on in our app in a different api, also only in arm64, I've opened another bug for this:
https://github.com/robovm/robovm/issues/1149
Please take a look.

**Comment by alexitelman** [comment] 2015-09-14 20:55
Hi, can you look at issue 1149 please?

**Comment by alexitelman** [comment] 2015-09-17 05:41
The download link is not available, where can I download RoboVM 1.8?

**Comment by badlogic** [comment] 2015-09-17 05:53
Either through JetBrain's plugin repository, or though
http://download.robovm.org/files.html

**Comment by alexitelman** [comment] 2015-09-17 05:55
Thanks. Can I continue working with jdk 7 with robo 1.8? Or do I have to upgrade to jdk 8?

**Comment by badlogic** [comment] 2015-09-17 05:56
You can continue to work with JDK 7. If you generate a new project, the
language level will be set to JDK 8. You can change that in the
build.gradle/pom.xml as well as within IDEA.

**Comment by alexitelman** [comment] 2015-09-17 05:59
Great, thanks!
Are there advantages to upgrading to jdk 8 in terms of RoboVM? Except using lambdas in our code?

**Comment by badlogic** [comment] 2015-09-17 06:12
No, lambdas are currently the only advantage.
