### ISSUE TITLE
RoboVM Studio 1.5.0 EAP (July 8) - Clojure 1.7.0 and Debug

### ISSUE THREAD

**Issue by chgraham** [robovm/robovm#1056] opened 2015-07-10 20:07 UTC
Default ("Click Me") cross-platform app with very minimal Clojure 1.7.0.

"RUN" works, but "DEBUG" aborts.
See the post with same title at RoboVM Google Group for more information.

Zipped example project "Baz" at:
https://drive.google.com/file/d/0B01dTzStLIUTUnJkZThienBfZDQ/view?usp=sharing

(Note that Clojure 1.7.0 JAR file was downloaded from clojure.org and added to this project as a library.)

**Comment by badlogic** [comment] 2015-07-10 20:08
Thanks for the repro case, we'll look into it asap.

**Comment by badlogic** [comment] 2015-07-27 11:55
This seems to be a duplicate of https://github.com/robovm/robovm/issues/903, which is supposed to be fixed, for exactly the method in question (`clojure.core$build_positional_factory$iter__6232__6236$fn__6237$fn__6238.invoke()`). Investigating.

**Comment by badlogic** [comment] 2015-07-27 12:20
Looks like the Clojure compiler may emit multiple line numbers per line, which shouldn't be possible.

![http://sht.tl/LEAnhh](http://sht.tl/LEAnhh)

This destroys our scope construction and leads to the exception in #903.

**Comment by badlogic** [comment] 2015-07-27 12:39
This should be fixed in the next nightly. You can download it from http://download.robovm.org/nightlies/robovm-studio/robovm-studio-1.5.1-SNAPSHOT.dmg in about 12 hours from now.

Thanks for reporting!

**Closed by badlogic** 2015-07-27 12:39 UTC
Labels: bug
