### ISSUE TITLE
wrong time in Calendar

### ISSUE THREAD

**Issue by hnvn** [robovm/robovm#342] opened 2014-05-19 03:02 UTC
Wrong time received from Calender:

``` Calendar.getInstance().getTime() ```

When I run this method on iPhone (4) the right , but wrong on the iPad (air)

**Comment by ntherning** [comment] 2015-01-04 15:04
I run this code on device and in the simulator (iOS 8.x):

```java
System.out.println(TimeZone.getDefault());
System.out.println(System.currentTimeMillis() / 1000);
System.out.println(new Date());
```

I should see `Europe/Stockholm` as timezone and get `GMT+1` as offset here in Sweden. Here's the output:

```
Device:
java.util.SimpleTimeZone[id=GMT,offset=0,dstSavings=3600000,useDaylight=false,startYear=0,startMode=0,startMonth=0,startDay=0,startDayOfWeek=0,startTime=0,endMode=0,endMonth=0,endDay=0,endDayOfWeek=0,endTime=0]
1420383165
Sun Jan 04 14:52:45 GMT+00:00 2015

Simulator:
libcore.util.ZoneInfo[id="Europe/Stockholm",mRawOffset=3600000,mEarliestRawOffset=3600000,mUseDst=true,mDstSavings=3600000,transitions=118]
1420383126
Sun Jan 04 15:52:06 GMT+01:00 2015
```

So to me it looks like `System.currentTimeMillis()` is correct. The problem is the default timezone on the device. Can you guys please run the same code snippet on your devices and compare with the simulator and let me know here please?

**Comment by BlueRiverInteractive** [comment] 2015-01-04 18:36
I'm getting the same results. The simulator shows the correct time and timezone

```
Device:
java.util.SimpleTimeZone[id=GMT,offset=0,dstSavings=3600000,useDaylight=false,startYear=0,startMode=0,startMonth=0,startDay=0,startDayOfWeek=0,startTime=0,endMode=0,endMonth=0,endDay=0,endDayOfWeek=0,endTime=0]
1420396406
Sun Jan 04 18:33:26 GMT+00:00 2015

Simulator:
libcore.util.ZoneInfo[id="Europe/Vienna",mRawOffset=3600000,mEarliestRawOffset=3600000,mUseDst=true,mDstSavings=3600000,transitions=140]
1420396347
Sun Jan 04 19:32:27 GMT+01:00 2015
```

**Comment by ntherning** [comment] 2015-01-05 08:28
To read the default timezone on iOS devices we resolve the symlink `/private/var/db/timezone/localtime` which points at the time zone data file. On iOS 6 this pointed to a file in `/usr/share/zoneinfo/` and we just [stripped this prefix](https://github.com/robovm/robovm/blob/97935cb710a14ae8468a715869f9ffd433aad826/rt/libcore/luni/src/main/java/libcore/util/TzDataRoboVM.java#L288) from the resolved path to get the default time zone (e.g. `/usr/share/zoneinfo/US/Pacific` -> `US/Pacific`). On iOS 8 (and maybe iOS 7?) `/private/var/db/timezone/localtime` resolves to files in `/usr/share/zoneinfo.default/` which breaks our code. We could instead loop through all available time zone ids and see which one the default path ends with. Should be more robust.

**Comment by ntherning** [comment] 2015-01-05 08:30
I believe this is fixed now but need to test on iOS 7 device as well.

**Comment by ntherning** [comment] 2015-01-07 10:44
Works fine on iOS 7 device as well. Closing as fixed.

**Closed by ntherning** 2015-01-07 10:44 UTC
