### ISSUE TITLE
Clojure Does Not Run - IntelliJ Plugin iOS Project

### ISSUE THREAD

**Issue by chgraham** [robovm/robovm#953] opened 2015-04-29 16:38 UTC
=========
OVERVIEW:
=========

I created this project:
https://drive.google.com/file/d/0B01dTzStLIUTNVRQQjJjWFpTNjA/view?usp=sharing

Using nightlies/idea/org.robovm.idea-1.1.1-SNAPSHOT-plugin-dist-20150429_021313-58.jar
( Using archives/idea/1.1.0/org.robovm.idea-1.1.0-plugin-dist.jar did not work either.)
  
Same crash, using either Clojure 1.6.0 or Clojure 1.7.0-beta2

Now, in robovm.xml, instead of simply adding:

  <forceLinkClasses>
    <pattern>clojure.**</pattern>
  </forceLinkClasses>

I let RoboVM tell me which patterns to add. So...

At each attempt to run the app on my iOS Simulator run configuration, RoboVM tells me I need to add another pattern. I end up with:

  <forceLinkClasses>
    <pattern>clojure.core__init</pattern>
    <pattern>clojure.core_proxy__init</pattern>
    <pattern>clojure.core_print__init</pattern>
    <pattern>clojure.genclass__init</pattern>
    <pattern>clojure.core_deftype__init</pattern>
    <pattern>clojure.core.protocols__init</pattern>
    <pattern>clojure.gvec__init</pattern>
  </forceLinkClasses>

It is when the last pattern
    <pattern>clojure.gvec__init</pattern>
is added that the following OUTPUT is produced
(until this last pattern is added I merely receive directions to add the next pattern).

Note that the "Line number must not be < 1" is the same error I get with trying to create and run a RoboVM iOS app using Clojure via lein-fruit (see issue #946).

=======
OUTPUT:
=======

The app (see Google Drive link, above) compiles and loads into the iOS Simulator then crashes:

[DEBUG] Loading default RoboVM config properties file: /Users/chgraham/Documents/d/RoboVM/RoboVMApp2/robovm.properties
[DEBUG] Loading default RoboVM config file: /Users/chgraham/Documents/d/RoboVM/RoboVMApp2/robovm.xml
[INFO] Building executable in /Users/chgraham/Documents/d/RoboVM/RoboVMApp2/robovm-build/tmp/RoboVM iOS Simulator/ios/x86
[INFO] Installation of app in /Users/chgraham/Documents/d/RoboVM/RoboVMApp2/robovm-build/tmp/RoboVM iOS Simulator/ios/x86
[INFO] classpath entry: /Users/chgraham/Documents/d/RoboVM/RoboVMApp2/build/resources/main
[INFO] classpath entry: /Users/chgraham/Documents/d/RoboVM/RoboVMApp2/build/classes/main
[INFO] classpath entry: /Users/chgraham/.m2/repository/org/clojure/clojure/1.6.0/clojure-1.6.0.jar
[INFO] classpath entry: /Users/chgraham/.m2/repository/org/codehaus/jsr166-mirror/jsr166y/1.7.0/jsr166y-1.7.0.jar
[INFO] boot classpath entry: /Users/chgraham/.gradle/caches/modules-2/files-2.1/org.robovm/robovm-objc/1.1.1-SNAPSHOT/bc5e4f8668c10219f06361e1d36902c393266cb6/robovm-objc-1.1.1-SNAPSHOT.jar
[INFO] boot classpath entry: /Users/chgraham/.gradle/caches/modules-2/files-2.1/org.robovm/robovm-rt/1.1.1-SNAPSHOT/85d736c327eebbc3b6aff61d7f500f0893db348a/robovm-rt-1.1.1-SNAPSHOT.jar
[INFO] boot classpath entry: /Users/chgraham/.gradle/caches/modules-2/files-2.1/org.robovm/robovm-cocoatouch/1.1.1-SNAPSHOT/45a193b8841edab31db3e59aa88fa3433999f6a2/robovm-cocoatouch-1.1.1-SNAPSHOT.jar
[INFO] Cleaning output dir /Users/chgraham/Documents/d/RoboVM/RoboVMApp2/robovm-build/tmp/RoboVM iOS Simulator/ios/x86
[WARNING] RoboVM has detected that you are running on a slow HDD. Please consider mounting a RAM disk.
To create a 2GB RAM disk, run this in your terminal:
SIZE=2048 ; diskutil erasevolume HFS+ 'RoboVM RAM Disk' `hdiutil attach -nomount ram://$((SIZE * 2048))`
See http://docs.robovm.com/ for more info
[DEBUG] Compiling classes using 8 threads
[DEBUG] Compiling clojure.core.ArrayChunk (ios x86 release)
[ERROR] Couldn't compile app
java.lang.IllegalArgumentException: Line number must not be < 1
	at com.robovm.debug.compiler.m.a(Unknown.java:48)
	at com.robovm.debug.compiler.DebugInfoPlugin.afterMethod(Unknown.java:305)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:768)
	at org.robovm.compiler.ClassCompiler.compile(ClassCompiler.java:287)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:242)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:331)
	at org.robovm.compiler.AppCompiler.compile(AppCompiler.java:375)
	at org.robovm.idea.compilation.RoboVmCompilerThread.doCompile(RoboVmCompilerThread.java:60)
	at org.robovm.idea.compilation.RoboVmCompilerThread.run(RoboVmCompilerThread.java:66)

**Comment by chgraham** [comment] 2015-04-29 16:42
I see in my post that the XML did not appear. Note that when I mention "pattern(s)" I am referring to "pattern" XML elements in the "forceLinkClasses" XML element.

**Comment by abram** [comment] 2015-05-04 01:36
I believe the "Line number must not be < 1" error is coming from https://github.com/robovm/robovm/issues/903. Try disabling your RoboVM license and then you may get a more useful error message.

**Comment by chgraham** [comment] 2015-05-04 20:22
Question: I'm in IntelliJ, how can I get your plug-in's build process to also compile my Clojure code ?

So... using your IntelliJ RoboVM plug-in, I can successfully run this Clojure app on RoBoVM-iOS, if before pressing the Run button, I first issue a "gradlew classes" command in a terminal window.

Note that I slightly changed my build.grade file (see below), but the crucial point is that the Clojure code is not being compiled when your IntelliJ plug-in is in charge of the build. If you look at the image I've provided, only Main.class was produced, none of the core... class files where created (unless I ran "gridlew classes" myself at the command line.

![clojure robovm ios app](https://cloud.githubusercontent.com/assets/1815620/7461532/fcb2daf6-f278-11e4-90be-2fe0b4962ada.png)

Here is the build.gradle file for this project:

buildscript {
    repositories {
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
        maven { url 'https://clojars.org/repo/' }
    }
    dependencies {
        classpath 'org.robovm:robovm-gradle-plugin:1.1.1-SNAPSHOT'
        classpath 'clojuresque:clojuresque:1.7.0'
    }
}

apply plugin: 'java'
apply plugin: 'robovm'
apply plugin: 'clojure'

repositories {
    mavenCentral()
    maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
    maven { url 'https://clojars.org/repo/' }
}

clojure {
    warnOnReflection = true
    aotCompile = true
}

ext {
    roboVMVersion = "1.1.1-SNAPSHOT"
}

robovm {
}

dependencies {
    compile "org.robovm:robovm-rt:${roboVMVersion}"
    compile "org.robovm:robovm-cocoatouch:${roboVMVersion}"
    compile "org.clojure:clojure:1.7.0-beta2"
    testCompile "junit:junit:4.12"
}

**Comment by ntherning** [comment] 2015-06-01 07:27
This is most likely a duplicate of #903. Closing this in favor of the other issue.

**Closed by ntherning** 2015-06-01 07:27 UTC
