### ISSUE TITLE
@IBOutletCollection-annotated methods are called before object initialization

### ISSUE THREAD

**Issue by magicgoose** [robovm/robovm#951] opened 2015-04-29 09:29 UTC
I have a class (which extends UIViewController), and it has a couple of instance variables. They are initialized in the declaration. Like the following:

    private UIButton[] row1 = new UIButton[3];
    private UIButton[] row2 = new UIButton[3];

And I have the method which is supposed to be called by iOS when loading storyboard, like this:

    @IBOutletCollection
    private void setButtons(NSArray<UIButton> buttons) {
        Assert.equals(6, buttons.size());
        for (int i = 0; i < 6; i++) {
            (i < 3 ? row1 : row2)[i % 3] = buttons.get(i);
        }
    }

AFAIK in Java it's not possible to call a method on uninitialized object. But when `setButtons` is called, these instance variables are `null`. How is that possible? And is it possible to fix?

**Comment by magicgoose** [comment] 2015-04-29 10:48
Update: seems like constructors and/or initialization block are never called. (simply as that)

**Comment by badlogic** [comment] 2015-04-29 11:48
There's already an issue for that on the tracker. As a work around you can
initialize your instance fields in viewDidLoad() of your controller.

**Comment by BlueRiverInteractive** [comment] 2015-04-29 19:40
Related issue: https://github.com/robovm/robovm/issues/894

**Comment by ntherning** [comment] 2015-08-13 09:08
Closing this as a duplicate of #894

**Closed by ntherning** 2015-08-13 09:08 UTC
Labels: duplicate
