### ISSUE TITLE
UnsatisfiedLinkError: Native Library libhfscompressor.dylib already loaded in another classloader

### ISSUE THREAD

**Issue by AgrarPirat** [robovm/robovm#867] opened 2015-03-24 00:16 UTC
For some odd reason, I'm forced to delete the ~/.gradle directory to be able to build a roboVM project. Once the directory is deleted and Android Studio is restarted, the app builds and executes just fine. But without deletion of the gradle directory, an `UnsatisfiedLinkError: Native Library libhfscompressor.dylib already loaded in another classloader` error happens. 

I tried to fix it by recreating the project using libGDX setup-ui. But without success. Cleaning the project as well as invalidating Android Studio's cache has also no effect. Neither did removing all roboVM bindings/libraries from the iOS build. Now I'm running out of ideas how this issue can be fixed.

It happens with roboVM 1.0.0 as well as roboVM 1.0.0-SNAPSHOT, libGDX 1.5.5 as well as 1.5.6-SNAPSHOT in Android Studio 1.1.0.
This is what the stacktrace looks like:

```
Failed to launch IOS Device

:ios:launchIOSDevice FAILED

:ios:launchIOSDevice (Thread[Daemon worker Thread 2,5,main]) completed. Took 4.989 secs.
               
FAILURE: Build failed with an exception.
               
* What went wrong:
Execution failed for task ':ios:launchIOSDevice'.
> Failed to launch IOS Device
               
* Try:         
Run with --debug option to get more log output.
               
* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':ios:launchIOSDevice'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
        at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:47)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:35)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:24)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.StartStopIfBuildAndStop.execute(StartStopIfBuildAndStop.java:33)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:71)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:69)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:69)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:70)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:34)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.DaemonHygieneAction.execute(DaemonHygieneAction.java:39)
        at org.gradle.launcher.daemon.server.exec.DaemonCommandExecution.proceed(DaemonCommandExecution.java:119)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:46)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
        at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
Caused by: org.gradle.api.GradleException: Failed to launch IOS Device
        at org.robovm.gradle.tasks.IOSDeviceTask.invoke(IOSDeviceTask.java:45)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 54 more
Caused by: java.lang.UnsatisfiedLinkError: Native Library /Users/x/.m2/repository/org/robovm/robovm-dist/1.0.0/unpacked/robovm-1.0.0/bin/libhfscompressor.dylib already loaded in another classloader
        at org.robovm.compiler.util.io.HfsCompressor.loadLib(HfsCompressor.java:43)
        at org.robovm.compiler.util.io.HfsCompressor.compress(HfsCompressor.java:60)
        at org.robovm.compiler.ClassCompiler.generateMachineCode(ClassCompiler.java:410)
        at org.robovm.compiler.ClassCompiler.access$000(ClassCompiler.java:130)
        at org.robovm.compiler.ClassCompiler$1.run(ClassCompiler.java:310)
               
               
BUILD FAILED   
               
Total time: 15.003 secs
Stopped 0 compiler daemon(s).
Received result DaemonCommandResult[type=CommandFailure, value=org.gradle.launcher.exec.ReportedException: org.gradle.internal.exceptions.LocationAwareException: Execution failed for task ':ios:launchIOSDevice'.] from daemon DaemonInfo{pid=275, address=[4ddf660d-c16e-43a9-a449-d61a5fbad240 port:59406, addresses:[/0:0:0:0:0:0:0:1, /127.0.0.1]], idle=true, context=DefaultDaemonContext[uid=3b706dc8-da0b-4819-a62a-fd1034ed915d,javaHome=/Library/Java/JavaVirtualMachines/jdk1.7.0_45.jdk/Contents/Home,daemonRegistryDir=/Users/x/.gradle/daemon,pid=275,idleTimeout=10800000,daemonOpts=-Xms128m,-Xmx512m,-Dfile.encoding=UTF-8,-Duser.country=US,-Duser.language=en,-Duser.variant]}.
```

**Comment by tajny** [comment] 2015-03-27 08:48
same here ( after update to robovm 1.0.0 from beta 4 ) 

```
Caused by: java.lang.UnsatisfiedLinkError: Native Library /Users/?/.m2/repository/org/robovm/robovm-dist/1.0.0/unpacked/robovm-1.0.0/bin/libhfscompressor.dylib already loaded in another classloader
	at org.robovm.compiler.util.io.HfsCompressor.loadLib(HfsCompressor.java:43)
	at org.robovm.compiler.util.io.HfsCompressor.compress(HfsCompressor.java:60)
	at org.robovm.compiler.ClassCompiler.generateMachineCode(ClassCompiler.java:410)
	at org.robovm.compiler.ClassCompiler.access$000(ClassCompiler.java:130)
	at org.robovm.compiler.ClassCompiler$1.run(ClassCompiler.java:310)
```

**Comment by badlogic** [comment] 2015-03-27 09:09
It seems the Gradle daemon reloads the RoboVM plugin everytime, so classes get loaded by different class loaders. This causes that exception. As a temporary fix, you can disable the Gradle daemon by opening the `gradle.properties` file and setting `org.gradle.daemon=false` instead of `true`.

**Comment by tajny** [comment] 2015-03-27 10:13
That works, thanks.

**Comment by AgrarPirat** [comment] 2015-03-28 11:08
Thanks for the advice, it works when the project is build at the terminal using `./gradlew :ios:launchIOSDevice`. 
Starting a build by clicking the green 'run' button in Android Studio still causes the same problem. Although the build configuration uses the same parameters (`Gradle project: ios` and `Tasks: launchIOSDevice`). 
I'm fine with that solution, thank you. Still, any ideas how to get the GUI build running again are appreciated.

**Comment by badlogic** [comment] 2015-03-28 11:10
Are you using the RoboVM IDEA plugin? That alsomuses Gradle for builds, so
there should be a way to disable the daemon, maybe within IDEA itself.

We will publish a new IDEA plugin very soon that will fix this issue.

**Comment by AgrarPirat** [comment] 2015-03-28 11:44
Awesome, I'll take a look at the RoboVM IDEA plugin. Thank you very much.

**Comment by ntherning** [comment] 2015-04-20 11:47
Does this work now with the latest RoboVM IntelliJ plugin? Please close it if it does.

**Comment by voidstarfire** [comment] 2015-04-23 09:43
I'm still getting this issue with the following

org.gradle.daemon=false
org.gradle.jvmargs=-Xms1024m -Xmx3000m
org.gradle.configureondemand=false

I cannot build iOS apps now, I'm using command line:  ./gradlew launchIOSDevice --stacktrace

Caused by: java.lang.UnsatisfiedLinkError: Native Library /Users/oliverdixon/.m2/repository/org/robovm/robovm-dist/1.1.0/unpacked/robovm-1.1.0/bin/libhfscompressor.dylib already loaded in another classloader

**Comment by voidstarfire** [comment] 2015-04-23 10:23
Restarting my computer resolved this?

**Comment by badlogic** [comment] 2015-04-23 10:35
Restarting resolved it as the Gradle daemon was still running due to a
previous gradle invocation before you changed the config. You should not
have this problem going forward.

**Comment by voidstarfire** [comment] 2015-04-23 10:44
I can confirm that calling ./gradlew --stop at the root of the project the calling ./gradlew --launchIOSDevice works

**Comment by ntherning** [comment] 2015-05-07 09:27
Still an issue? I'm closing this. Please reopen if it's still a problem.

**Closed by ntherning** 2015-05-07 09:27 UTC

**Comment by kutoman** [comment] 2015-05-23 18:25
I'm getting the same error as soon as I launch the simulator (launchIPhoneSimulator) a 2nd time. 
My properties / configurations are:
classpath 'org.robovm:robovm-gradle-plugin:1.2.0'
org.gradle.daemon=false
