### ISSUE TITLE
No Stacktrace for exception in global queue thread.

### ISSUE THREAD

**Issue by ilyaY** [robovm/robovm#482] opened 2014-09-09 12:28 UTC
```
public static void main(String[] args) {
    DispatchQueue.getGlobalQueue(0, 0).async(new Runnable() {
        @Override
        public void run() {
            throw new RuntimeException();
        }
    });
}
```

This simple main will produce
Unhandled exception: java/lang/RuntimeException
output instead of Stacktrace. In main thread Stacktrace is posted as expected.

**Comment by ntherning** [comment] 2015-01-07 11:05
This is a duplicate of #689. We will use that issue instead as it contains more info on the problem.

**Closed by ntherning** 2015-01-07 11:05 UTC
