### ISSUE TITLE
CTFrame.getLines marshaler error

### ISSUE THREAD

**Issue by tomfisher** [robovm/robovm#1024] opened 2015-06-18 09:27 UTC
The following code: 
```
	private static List<CTLine> wrapLines(NSAttributedString astring, float wrapWidth) {
	      CTFramesetter fs =  CTFramesetter.create(new NSAttributedString());
	      CGPath path = CGPath.createWithRect(new CGRect(0, 0, 100, 100), CGAffineTransform.Identity());
	      CTFrame frame = fs.createFrame(new CFRange(0, 0), path, new CTFrameAttributes());
	      return frame.getLines();
	  }
```

results:

```
java.lang.InstantiationException: 
	at org.robovm.rt.VM.allocateObject(Native Method)
	at org.robovm.rt.bro.NativeObject$Marshaler.toObject(NativeObject.java:88)
	at org.robovm.apple.corefoundation.CFType$Marshaler.toObject(CFType.java:68)
	at org.robovm.apple.corefoundation.CFType$Marshaler.toObject(CFType.java:51)
	at org.robovm.apple.coretext.CTLine$AsListMarshaler.toObject(CTLine.java:44)
	at org.robovm.apple.coretext.CTFrame.getLines(Native Method)
	at com.mb.wb.robovm.demo.NativeMain.wrapLines(NativeMain.java:48)
```

**Comment by tomfisher** [comment] 2015-06-18 09:30
I'm using Robovm 1.3

**Comment by ntherning** [comment] 2015-07-01 07:54
Managed to reproduce this with the most recent code and also figure out what the problem is. @BlueRiverInteractive the problem is the signature of the `CTFrame.getLines()` method

```java
    @Bridge(symbol="CTFrameGetLines", optional=true)
    public native @org.robovm.rt.bro.annotation.Marshaler(CTLine.AsListMarshaler.class) List<CTLine> getLines();
```

and the `CTLine.AsListMarshaler` class

```java
    public static class AsListMarshaler {
        @MarshalsPointer
        public static List<?> toObject(Class<? extends CFType> cls, long handle, long flags) {
            CFArray o = (CFArray) CFType.Marshaler.toObject(cls, handle, flags);
            if (o == null) {
                return null;
            }
            return o.toList(CTLine.class);
        }
```

`cls` in the marshaler will be `java.util.List` (an interface) but must be a subclass of `CFType` in the call to `CFType.Marshaler.toObject()`. I think the proper fix would be to ignore `cls` and just pass in `CFArray.class`:

```java
CFArray o = (CFArray) CFType.Marshaler.toObject(CFArray.class, handle, flags);
```

I had a look through other `AsListMarshaler` classes and I think they all suffer from this problem. So we need to go through them all I'm afraid.

**Comment by BlueRiverInteractive** [comment] 2015-07-02 13:23
Should be fixed in the next nightly.

**Closed by BlueRiverInteractive** 2015-07-02 13:23 UTC
Labels: bug
